#!/usr/bin/env bash


if [ "z${DIR}" == "z" ]; then
	echo "Do not use this defaults file this way. It needs a DIR specified";
	exit 1;
fi;



ARCH=${ARCH:-arm}
KERNEL_VERSION=${KERNEL_VERSION:-4.4.36}
CROSS_COMPILE=${CROSS_COMPILE:-arm-cortexa9_neon_l4-linux-gnueabihf-}
HOST=${HOST:-arm-cortexa9_neon_l4-linux-gnueabihf}

BUILDDIR=${BUILDDIR:-${DIR}/build}

KCONFIG=${DIR}/extconfigs/linux-${KERNEL_VERSION}
KERNEL=${DIR}/kernels/linux-${KERNEL_VERSION}
RKCRC=${DIR}/submodules/rkflashtool/rkcrc
INITRAMFS=${DIR}/initramfs


OFILESD=${BUILDDIR}/rk3188_sdboot.img
OFILENAND=${BUILDDIR}/rk3188_nand.img


