#!/bin/sh


[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc

# Set up our filesystems

mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc

echo 0 > /proc/sys/kernel/printk

mdev -s

# Create the console

modprobe fbcon

echo "What's up?"

/bin/sh


exec /sbin/init


